[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  NODE_VERSION = "20"

# Enable Next.js runtime - this plugin handles everything automatically
[[plugins]]
  package = "@netlify/plugin-nextjs"
